# Generated by Django 4.1.3 on 2022-12-07 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='stories', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'jpg', 'webp', 'jpeg', 'png'])])),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
