# Generated by Django 4.1.3 on 2022-12-05 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(upload_to='stories', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'jpg', 'webp', 'jpeg', 'png'])]),
        ),
    ]
