# Generated by Django 4.1.3 on 2023-01-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-create_at',), 'verbose_name': 'Сторис', 'verbose_name_plural': 'Сторисы'},
        ),
    ]
