# Generated by Django 4.1.3 on 2022-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
