# Generated by Django 4.1.3 on 2022-12-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ('-id',)},
        ),
    ]
